veBAL/getVeBAL base branch
balancer-labs/frontend-v2 pull request #1395
Opened 2022-02-10 02:26 UTC by evgenyboxer

- initial impl.
- feat: impl. lockable tokens
- fix: lint
- feat: init myVeBAL
- Add useVeBalQuery
- feat: initial work on the VeBalForm
- refactor: extract veBAL contract into a balancer contracts

# Description

Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2022-03-03 14:59 UTC, garethfuller reviewed
This is my first pass. Code looks great, really clean and well structured.

I talked with Pon/Fernando about the term 'Unlock', lets use the word 'Redeem' instead. Please replace all references to Unlock in component names, labels and routes.

2022-03-03 14:59 UTC, garethfuller commented on src/composables/queries/useAllowancesQuery.ts
> +    return allowances;
I think this was probably to log allowances right? Can we revert to original please.

2022-03-03 14:59 UTC, garethfuller commented on src/plugins/router.ts
> -  },
Why has the migration path been deleted here?

2022-03-14 16:02 UTC, garethfuller commented
@evgenyboxer when unlocking, the link back to the vebal page is broken.

2022-03-14 16:03 UTC, garethfuller commented
@evgenyboxer when my lock expired, I was unable to extend the lock again, it just kept reverting the tx. I had to unlock and then relock.

2022-03-17 09:56 UTC, markusbkoch commented
The veBAL dashboard tells me I have no BPT to lock on this address 0x67dc6f6ffa7De114c33144f3b1630Fd1Eecd27dD, even though I do
![image](https://user-images.githubusercontent.com/34865315/158783873-be51221a-da3a-4ca1-818b-c4cfb35ed240.png)

The lock UI does recognize them
![image](https://user-images.githubusercontent.com/34865315/158783994-260b3991-360b-4590-8dbb-20d732b1b940.png)

The only relevant thing I can think of is that I just withdrew BPT from the veBAL contract, so maybe there's an unhandled edged case in the dashboard that causes it to show like this? cc @garethfuller

2022-03-17 12:01 UTC, timjrobinson commented
@markusbkoch That is fixed, was just not showing the BPT value unless you had veBAL locked.

2022-03-18 18:26 UTC, TomAFrench requested changes

2022-03-18 18:26 UTC, TomAFrench commented on src/composables/useTime.ts
> +  const daysSinceThursday = (date.getDay() - 4) % 7;
```suggestion
  const daysSinceThursday = (date.getDay() - 4 + 7) % 7;
```

This doesn't work for Mon-Wed currently as it doesn't handle negatives correctly so we need to bump up by 7

2022-03-18 18:27 UTC, TomAFrench commented on src/composables/useTime.ts
> +  const daysSinceThursday = (date.getDay() - 4) % 7;
Granted, I think this bug got added by copy-pasting my snippet.

2022-03-21 13:59 UTC, garethfuller commented
> Is this working correctly? total at the bottom says 0.0091 vs actual says 0.0086 veBAL
> 
> <img alt="Screen Shot 2022-03-20 at 4 18 24 PM" width="892" src="https://user-images.githubusercontent.com/79888567/159184389-76254d42-f070-4824-b2f6-ed0581d971ce.png">

@zekraken-bot the Total voting escrow value in the form is what you get after you've locked. The value on the right is your current veBAL. If this is not clear enough, we may need to change labels. cc @pkattera

2022-03-22 13:19 UTC, merged