Tokenomics - APR
balancer-labs/frontend-v2 pull request #1516
Opened 2022-03-22 07:33 UTC by 1saf

# Description

Brings in the APR calculations for staked pools

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2022-03-22 09:24 UTC, garethfuller reviewed
@1saf There seems to be a lot of changes here that are unrelated to the APR change?

2022-03-31 13:27 UTC, TomAFrench reviewed
Things look ok other than a magical factor of 16.48 cropping up. I think we might be overcomplicating things by building so many maps of intermediate steps.

I'd separate the maths for calculating the APR for a pool out into a separate function and then iterate over the gauges once rather than 3+ times as we're doing here. This would be easier to parse.

2022-04-05 20:05 UTC, garethfuller requested changes
Looks pretty good. Main thing is that for ranges displayed it should include all APR components, not just the staking APR.

A couple of things missing
- Totals in APR tooltips should be a range and include the staking APRs
- APR on the pool page stat card should be a range and include the staking APRs
- Invest flow weekly yield should be a range using total APR range (maybe I can help with this part tomorrow?)

<img width="242" alt="Screenshot 2022-04-05 at 20 22 43" src="https://user-images.githubusercontent.com/2406506/161839943-cd4baae0-43ce-4474-b921-30b7142ad1b2.png">
<img width="260" alt="Screenshot 2022-04-05 at 20 24 53" src="https://user-images.githubusercontent.com/2406506/161839945-c0544f54-b3af-49f1-8d0e-190034460236.png">

2022-04-05 20:05 UTC, garethfuller commented on src/services/staking/utils.ts
> +  });
Remove before merge

2022-04-06 09:57 UTC, 1saf commented on src/composables/useNumbers.ts
> +  percent_lg = '0,0%'
doesnt work with fnum2

2022-04-06 09:57 UTC, 1saf commented on src/lib/utils/index.ts
> +}
will do

2022-04-06 09:58 UTC, 1saf commented on src/pages/index.vue
> +    {{ gaugeAprMap }}
to remove

2022-04-06 09:59 UTC, 1saf commented on src/services/balancer/contracts/contracts/token-admin.ts
> +  }
yeah something to visit

2022-04-06 19:42 UTC, merged