Show invest price impact when it is less than 0.01% (Closes #1762)
balancer-labs/frontend-v2 pull request #1771
Opened 2022-04-22 20:23 UTC by alter-eggo

# Description
This pr improves invest price impact. It is shown '< 0.01%' if less than 0.01% and greater than 0.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2022-04-26 10:30 UTC, evgenyboxer commented on src/composables/useNumbers.ts
> +  returnLessBasicPoint?: boolean; // If true, return less than basic point (< 0.01%) instead of 0.00%, if num < 0.00005
I think you meant `basis` point yeah?

2022-04-26 10:34 UTC, evgenyboxer commented on src/composables/useNumbers.ts
> +      return '< 0.01%';
I think we should prob be consistent and always return it without passing a config option.
Thoughts @garethfuller?

2022-04-26 15:01 UTC, alter-eggo commented on src/composables/useNumbers.ts
> +  returnLessBasicPoint?: boolean; // If true, return less than basic point (< 0.01%) instead of 0.00%, if num < 0.00005
yea, thank you. I meant `basis` point

2022-04-27 08:44 UTC, garethfuller requested changes

2022-05-05 13:53 UTC, garethfuller commented
I needed to move the conditional within the isPercentage block so it didn't affect all number formatting. Closing in favour of #1834

2022-05-05 13:53 UTC, closed without merging