Remove "Incl." text from veBal banner
balancer-labs/frontend-v2 pull request #2002
Opened 2022-06-20 09:46 UTC by sssmi

# Description

[Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.](https://github.com/balancer-labs/frontend-v2/issues/1695)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2022-07-01 05:20 UTC, alter-eggo requested changes

2022-07-01 05:20 UTC, alter-eggo commented on src/components/contextual/pages/pools/VeBalPoolTable.vue
> + * PROPS & EMITS
seems there are no emits here

2022-07-01 05:20 UTC, alter-eggo commented on src/components/tables/PoolsTable/PoolsTableActionsCell.vue
> + */
redundant comment

2022-07-01 05:20 UTC, alter-eggo commented on src/components/contextual/pages/pools/UnstakedPoolsTable.vue
> +  const hiddenCols = ['poolVolume', 'poolValue', 'migrate', 'lockedEndDate'];
there is no need in computed function here

2022-07-01 05:20 UTC, alter-eggo commented on src/components/contextual/pages/pools/VeBalPoolTable.vue
> +const hiddenColumns = computed(() => {
same, no need in computed here

2022-07-01 06:58 UTC, timjrobinson commented
I'm seeing "Stake" instead of lock on the 80/20 pool on Goerli. 

![2022-07-01-155551_1584x64_scrot](https://user-images.githubusercontent.com/525534/176841418-fff4c891-e1a0-41c4-a110-91392a936ab9.png)

2022-07-01 07:08 UTC, timjrobinson commented on src/components/tables/PoolsTable/PoolsTable.vue
> +    id: 'lockedEndDate',
`lockEndDate` sounds more correct in english.

2022-07-01 07:08 UTC, timjrobinson commented on src/components/tables/PoolsTable/PoolsTable.vue
> +  return lockedEndDate ? format(lockedEndDate, PRETTY_DATE_FORMAT) : '—';
Same here with `lockEndDate`

2022-07-01 09:43 UTC, pkattera commented
> I'm seeing "Stake" instead of lock on the 80/20 pool on Goerli.
> 
> ![2022-07-01-155551_1584x64_scrot](https://user-images.githubusercontent.com/525534/176841418-fff4c891-e1a0-41c4-a110-91392a936ab9.png)

@timjrobinson I also see 'Stake' on Goerli and Kovan. I believe this is due a bug due to that specific pool being set up incorrectly on Kovan. 

I have tested this on Mainnet and I see the correct 'Lock' button:

<img width="1074" alt="Screen Shot 2022-07-01 at 10 40 01 AM" src="https://user-images.githubusercontent.com/1121139/176870054-dc82c614-c08b-4585-8e48-22408a475960.png">

2022-07-04 01:30 UTC, timjrobinson approved these changes

2022-07-04 01:43 UTC, merged