Pool migration
balancer-labs/frontend-v2 pull request #2083
Opened 2022-07-21 13:57 UTC by alter-eggo

# Description

This pr adds new pool migration support

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2022-08-05 15:04 UTC, garethfuller reviewed
Looks like the defaults of BalBtn might have been changed. This text should be centred.

<img width="421" alt="Screenshot 2022-08-05 at 16 03 34" src="https://user-images.githubusercontent.com/2406506/183105411-c713921d-2f78-4def-8fb5-939c6d3f7abf.png">

2022-08-05 15:08 UTC, garethfuller reviewed
In the migration preview modal the total value seems to be a reactive property that goes to zero when the migration is complete. This shouldn't be the case, it should be a static value that even when the migration is complete stays the same.

Also, when the migration is complete, as in the screenshot, there should be a button linking to the toPool page with text like "Got to new pool". @pkattera what do you think about wording here?

<img width="458" alt="Screenshot 2022-08-05 at 16 05 03" src="https://user-images.githubusercontent.com/2406506/183105678-e3b9c032-70c8-4c90-923d-e39fa2777446.png">

2022-08-05 15:15 UTC, pkattera commented
> Also, when the migration is complete, as in the screenshot, there should be a button linking to the toPool page with text like "Go to new pool". @pkattera what do you think about wording here?

Yes, let's using the wording: `Go to new pool`

2022-08-08 14:12 UTC, garethfuller requested changes

2022-08-08 14:12 UTC, garethfuller commented on src/composables/pools/usePoolMigration.ts
> +  async function approveMigration(
I think this function is too big. It should be split up if possible into smaller more concise functions.

2022-08-08 14:15 UTC, garethfuller commented on src/composables/pools/usePoolMigration.ts
> +    const gasLimit = MAX_GAS_LIMIT;
As in, where did you get 8e6 from?

2022-08-09 06:04 UTC, alter-eggo commented on .env.development
> +VUE_APP_NETWORK=5
yeah, it was temporary, because migration cannot be performed on mainnet now. fixed

2022-08-09 06:26 UTC, alter-eggo commented on src/components/forms/pool_actions/MigrateForm/types.ts
> +  BBAUSD_POOL = 'bbaUSDPool',
no reason now, removed

2022-08-09 07:16 UTC, alter-eggo commented on src/composables/pools/usePoolMigration.ts
> +    const gasLimit = MAX_GAS_LIMIT;
ah, I took this value from sdk example, and then forgot to fix

2022-08-10 13:01 UTC, garethfuller commented
Could we not use `usePoolsQuery` [here](https://github.com/balancer-labs/frontend-v2/blob/pool-migration/src/components/forms/pool_actions/MigrateForm/MigrateForm.vue#L37-L38) instead to reduce fetching:
```ts
const poolsQuery = usePoolsQuery(ref([]), {}, { poolIds: [fromPoolId, toPoolId]);
```

2022-08-22 15:55 UTC, garethfuller commented on src/composables/pools/usePoolMigration.ts
> +    query = migrationFn.value(amount, isStaked, expectedBptOut); // TODO apply slippage here.
For when you get back @alter-eggo, the `expectedBptOut` here should not be passed directly as a limit. This 'limit' value is actually the minBptOut which is the minimum amount of BPT the user wants to receive or the transaction should fail. This is why we have a user setting called slippage. Please use it here to adjust this value, see `useSlippage` composable. You probably want to do something like:
```suggestion
    const minBptOut = minusSlippageScaled(expectedBptOut);
    query = migrationFn.value(amount, isStaked, minBptOut); // TODO apply slippage here.
```

2022-09-21 18:15 UTC, merged