Use gauge reward helper contract to claim rewards on layer 2s
balancer-labs/frontend-v2 pull request #2392
Opened 2022-11-07 09:13 UTC by 1saf

# Description

Currently gauge rewards shown on our front-end for alternate chains are not accurate. This change changes the pending rewards figures to come from the helper contract as well as claiming through the helper contract.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [X] Code refactor / cleanup
- [ ] Documentation or wording changes
- [X] Other

## How should this be tested?

Claiming and pending rewards behaviours should remain unbroken.

## Visual context
N/A

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [X] I have commented my code where relevant, particularly in hard-to-understand areas
- [X] If package-lock.json has changes, it was intentional.
- [X] The base of this PR is `master` if hotfix, `develop` if not

2022-11-08 11:00 UTC, garethfuller requested changes

2022-11-08 11:00 UTC, garethfuller commented on src/services/balancer/gauges/gauges.decorator.ts
> +  }
I'd just update `resetMulticaller` to take the abi as a param and then update usage in this class.
```suggestion
  private resetMulticaller(abi): Multicaller {
    return new Multicaller(this.config.network.key, this.provider, abi);
  }
```

2022-11-14 09:40 UTC, 1saf commented on src/components/btns/ClaimRewardsBtn/ClaimRewardsBtn.vue
> +);
Will throw into the method

2022-11-14 09:43 UTC, 1saf commented
Addressed comments.

2022-11-23 16:29 UTC, garethfuller approved these changes

2022-11-23 16:29 UTC, merged