Soft page transition animations
balancer-labs/frontend-v2 pull request #2552
Opened 2022-12-12 14:55 UTC by pkattera

# Description

This PR adds page transitions using opacity to soften the appearance as content fades in between pages.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [x] Other: Softer page transition animations

## How should this be tested?

Make sure no pages have broken with the changes. Page content should appear with a soft fade in from opacity: 0 to opacity: 1. 

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

2022-12-12 15:19 UTC, pkattera commented on src/components/contextual/pages/pool/invest/InvestPage.vue
> +  <Transition appear name="appear">
On pages like this, the only thing that changed was adding the <Transition></Transition> tags.

2022-12-13 11:37 UTC, garethfuller requested changes
I believe this should only be wrapped around the components in src/pages and nothing else. I see you've done it around layouts but I don't think that will have any effect when you change pages because the layout mostly stays the same. You have also used in on the InvestPage.vue component which is not an actual page, sorry the naming is misleading.

2022-12-13 14:39 UTC, pkattera commented
@garethfuller 
> I believe this should only be wrapped around the components in src/pages and nothing else. I see you've done it around layouts but I don't think that will have any effect when you change pages because the layout mostly stays the same. 

The main reason for it was to apply the same animation for the Navigation. I ended up removing the Transition from defaultLayout and added it to the Navigation component (which lives outside the other pages). 

> You have also used it on the InvestPage.vue component which is not an actual page, sorry the naming is misleading.

I'd like for the first screens of the invest, withdraw and migrate pages/modals to also include the same soft transition. I've applied them to `migrate` and `withdraw` which are actual pages. It looks like the invest page is driven by `InvestPage`. The functionality works as intended using the transition here, but is there a better place for me to add it?

2022-12-13 15:23 UTC, garethfuller commented
@pkattera so for example in defaultLayout.vue you would replace `<router-view :key="$route.path" />` with:
```vue
<router-view v-slot="{ Component, route }">
  <transition name="appear">
    <component :is="Component" />
  </transition>
</router-view>
```
And then you can do the same BlankLayout, ContentLayout and FocussedLayout.

2022-12-15 11:08 UTC, pkattera commented
Closing this PR in favor of #2571

2022-12-15 11:08 UTC, closed without merging