fix: don't redirect after manual wallet switch if on correct page
balancer-labs/frontend-v2 pull request #2557
Opened 2022-12-12 19:01 UTC by Matthews3301

# Description

If the user is manually switches networks via wallet to a network the url points to, don't reload the page.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

2022-12-13 11:42 UTC, garethfuller requested changes

2022-12-13 11:42 UTC, garethfuller commented on src/components/navs/AppNav/AppNavNetworkSelect.vue
> +  () => chainId.value,
Can this not just be:
```suggestion
  chainId,
```

2022-12-13 11:42 UTC, garethfuller commented on src/components/navs/AppNav/AppNavNetworkSelect.vue
> +      }
Use naming to make conditional a little clearer.
```suggestion
  (newChainId, oldChainId) => {
    if (newChainId && oldChainId && oldChainId !== newChainId && networkId.value !== newChainId) {
      const newNetwork = allNetworks.value.find(n => Number(n.key) === newChainId);
      if (newNetwork) {
        document.body.style.display = 'none';
        localStorage.setItem('networkId', newChainId.toString());
        setWindowLocation(getNetworkChangeUrl(newNetwork));
      }
```

2022-12-13 12:13 UTC, alter-eggo approved these changes

2022-12-14 14:40 UTC, garethfuller approved these changes

2022-12-14 14:40 UTC, merged