Fix approval flow in gnosis safe
balancer-labs/frontend-v2 pull request #2588
Opened 2022-12-20 15:25 UTC by alter-eggo

# Description
Change signature approval to tx approval if user uses gnosis safe wallet

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2022-12-20 23:35 UTC, Matthews3301 commented
@alter-eggo I'm wondering, maybe it would be better to instead of modifying the array of actions, to modify the logic of the sign action.

E.g. in:
https://github.com/balancer-labs/frontend-v2/blob/3cdf0e26d6717dcd9df002c7cee00e13c38d3bdd/src/composables/useSignRelayerApproval.ts#L43

Make this a conditional logic, and if on gnosis, use `isSignAction: false`.

2022-12-21 07:53 UTC, alter-eggo commented
@Matthews3301 thanks for your help here! 
but seems it won't solve the problem, as it still will call the same action. `isSignAction` is used only for specific handling of sign action in `BalActionSteps` component.

2022-12-21 10:12 UTC, Matthews3301 commented
@alter-eggo Sorry, that's what I mean: changing `isSignAction` parameter and also the action. It's more efficient to have it in `useSignRelayerApproval.ts` as it'll fix it in all places signing is currently used.

2022-12-21 15:00 UTC, alter-eggo commented
hm, yeah, makes sense, I will fix it

2022-12-21 15:30 UTC, Matthews3301 commented
I tested both actions locally and they work 👍 Haven't tested in Gnosis Safe.

2022-12-21 15:30 UTC, Matthews3301 approved these changes

2023-01-03 14:17 UTC, garethfuller requested changes
Ahh I think this is completely wrong. There is some confusion because for the Cowswap interface in the Swap UI you need to approve the gnosis relayer. That has nothing to do with signing the Balancer batch relayer.

The logic should be:
```
if provider === 'gnosis'
    inject approval tx rather than signature (but for the same relayer)
```

2023-01-03 14:17 UTC, garethfuller commented on src/composables/useSignRelayerApproval.ts
> +    const provider = lsGet('connectedProvider');
Instead of getting this from local storage, can we get it from the active state in useWeb3?

2023-01-05 10:17 UTC, Matthews3301 commented on src/composables/useSignRelayerApproval.ts
> +    RelayerType.GNOSIS
What if we change this to `Relayer`, i.e. the type of approval which is requested, not just Gnosis (Cowswap). This will include batch relayer.

2023-01-05 20:49 UTC, Matthews3301 commented
@garethfuller would you mind checking now? I changed the logic.

2023-01-06 12:35 UTC, garethfuller commented
@Matthews3301 thanks, I also had a go at a larger refactor of approvals because they were all over the place. I:
- Moved all approval composables under one 'approvals' folder.
- Renamed `useRelayerApproval` > `useRelayerApprvalTx` since it was specifically for handling a tx approval.
- Renamed `useSignRelayerApproval` > `useRelayerApproval` since it actually handles both cases, e.g. signature + fallback.

2023-01-09 12:23 UTC, garethfuller approved these changes
I was able to add liquidity to a boosted pool on polygon via a Safe wallet. It asked me to approve the relayer with a tx rather than a signature as expected.

2023-01-09 12:28 UTC, alter-eggo reviewed
thanks for your help here guys. from the code side lgtm

2023-01-09 13:51 UTC, merged