Feature/user lock composition
balancer-labs/frontend-v2 pull request #2773
Opened 2023-02-07 17:20 UTC by agualis

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

2023-02-07 18:16 UTC, agualis commented on src/composables/useUserPoolPercentage.ts
> +    // return lock.value?.lockedAmount || '0';
@garethfuller I started using lockedAmount but I think that I should use `lockedFiatTotal` instead, which is not a fiat, so probably better renaming it to `lockedBalanceTotal` or `lockedAmountTotal`. Am I wrong?

2023-02-07 18:23 UTC, agualis commented
@timjrobinson Could you check that the calculations looks good in the preview? (I used your account to test it but I could be missing something).

https://feature-user-lock-compositio.balancer-d6h.pages.dev/#/ethereum/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014

2023-02-08 11:36 UTC, agualis commented on src/composables/useUserPoolPercentage.ts
> +    // return lock.value?.lockedAmount || '0';
Update: I saw that you already renamed it in another PR.

2023-02-13 16:57 UTC, garethfuller requested changes
Seems package-lock has been committed with changes when it shouldn't have been?

2023-02-14 09:34 UTC, garethfuller approved these changes
lgtm!

2023-02-14 09:34 UTC, merged