Error states for trade UI
balancer-labs/frontend-v2 pull request #387
Opened 2021-05-25 11:18 UTC by Destiner

2021-05-25 11:37 UTC, Destiner commented on src/composables/trade/useValidation.ts
> +}
Added enum for better separation of concerns (composable doesn't have to know about localization) and type safety.

2021-05-25 11:38 UTC, Destiner commented on src/composables/trade/useValidation.ts
> +    if (!auth.isAuthenticated.value) return TradeValidation.NO_ACCOUNT;
Standartizing "not authenticated" error + fixed a bug where the condition was always false.

2021-05-27 10:37 UTC, garethfuller requested changes
Thanks for this Timur. I have a more general comment about the TradeError component. Really we should be using the BalAlert component for these types of error messages. However, it's not currently built to support exactly what you're trying to do here so I'll update it and commit to this PR if that's ok.

2021-05-27 13:58 UTC, garethfuller approved these changes

2021-05-28 06:14 UTC, Destiner commented on src/components/cards/TradeCard/TradeCard.vue
> +      return undefined;
Done

2021-05-28 06:24 UTC, merged